#!/bin/bash

set -e -o pipefail

PUBLISH_DIR=/tmp/RoadCaptain
VERSION=$(grep Version Directory.Build.props | sed -e 's/<Version>//g' -e 's/<\/Version>//g' | tr -d '\t ')
SIGNING_IDENTITY="Developer ID Application: Codenizer BV (44HHP3V8VR)" # matches Keychain Access certificate name
DISK_IMAGE=/tmp/RoadCaptain.dmg

./packaging/build-macos-app "$PUBLISH_DIR" "$VERSION" "Runner" "$SIGNING_IDENTITY"
./packaging/build-macos-app "$PUBLISH_DIR" "$VERSION" "RouteBuilder" "$SIGNING_IDENTITY"

echo "[INFO] Creating disk image"

./packaging/create-dmg --volname "RoadCaptain" --volicon ./src/RoadCaptain.App.Shared/icon.icns --window-pos 200 120 --window-size 800 533 --icon-size 128 --icon "RoadCaptain RouteBuilder.app" 200 40 --icon "RoadCaptain Runner.app" 200 260 --app-drop-link 600 40 --background "./src/RoadCaptain.App.Shared/Assets/installer-background.jpg" --codesign A357F29F30B7179DCBA515D2A6ECE77620951CBD "$DISK_IMAGE" "$PUBLISH_DIR"

echo "[INFO] Notarizing disk image"

xcrun notarytool submit "$DISK_IMAGE" --keychain-profile "AC_PASSWORD" --wait
xcrun stapler staple "$DISK_IMAGE"

echo "[INFO] Build complete"
