#!/bin/sh

PUBLISH_DIR=/tmp/RoadCaptain
VERSION=$(grep Version Directory.Build.props | sed -e 's/<Version>//g' -e 's/<\/Version>//g' | tr -d '\t ')
SIGNING_IDENTITY="Developer ID Application: Codenizer BV (44HHP3V8VR)" # matches Keychain Access certificate name

./packaging/build-macos-app "$PUBLISH_DIR" "$VERSION" "Runner" "$SIGNING_IDENTITY"
./packaging/build-macos-app "$PUBLISH_DIR" "$VERSION" "RouteBuilder" "$SIGNING_IDENTITY"

echo "[INFO] Creating disk image"
./packaging/create-dmg --volname "RoadCaptain" --volicon ./src/RoadCaptain.App.Shared/icon.icns --window-pos 200 120 --window-size 800 533 --icon-size 128 --icon "RoadCaptainRouteBuilder.app" 200 40 --icon "RoadCaptainRunner.app" 200 260 --app-drop-link 600 40 --background "./src/RoadCaptain.App.Shared/Assets/installer-background.jpg" --codesign A357F29F30B7179DCBA515D2A6ECE77620951CBD "/tmp/RoadCaptain.dmg" "/tmp/RoadCaptain"

echo "[INFO] Notarizing disk image"

xcrun notarytool submit /tmp/RoadCaptain.dmg --keychain-profile "AC_PASSWORD" --wait
xcrun stapler staple /tmp/RoadCaptain.dmg

echo "[INFO] Build complete"