name: build-and-test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - site/**
  pull_request:
    branches: [ main ]
    paths-ignore:
      - site/**

jobs:
  build_win:
    timeout-minutes: 20

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: dotnet build RoadCaptain.Windows.slnf --verbosity quiet -c Release -p:SkipInvalidConfigurations=true
    - name: Test
      run: dotnet test RoadCaptain.Windows.slnf  --no-build --verbosity quiet -c Release

#  build_macos-x64:
#
#    runs-on: macos-11
#
#    steps:
#    - uses: actions/checkout@v3
#    - name: Build
#      run: dotnet build RoadCaptain.MacOS.slnf --verbosity quiet -c Release -p:SkipInvalidConfigurations=true
#    - name: Test
#      run: dotnet test RoadCaptain.MacOS.slnf --no-build --verbosity quiet -c Release
         
  build_linux-x64:
    timeout-minutes: 20

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: dotnet build RoadCaptain.Linux.slnf --verbosity quiet -c Release -p:SkipInvalidConfigurations=true
    - name: Test
      run: dotnet test RoadCaptain.Linux.slnf --no-build --verbosity normal -c Release
