name: build-api-prod

on:
  workflow_dispatch:
  push:
    tags: 
    - releases/[0-9]+.[0-9]+.[0-9]+
    - releases/[0-9]+.[0-9]+.[0-9]+.[0-9]+
    - prereleases/[0-9]+.[0-9]+.[0-9]+
    - prereleases/[0-9]+.[0-9]+.[0-9]+.[0-9]+
    paths-ignore:
      - site/**
      - src/RoadCaptain.App.Runner/** # Don't trigger on Runner only changes
      - src/RoadCaptain.App.RouteBuilder/** # Don't trigger on RouteBuilder only changes

jobs:
  build_api_linux-x64:
    timeout-minutes: 20

    runs-on: ubuntu-latest

    env:
      CONFIGURATION: Release
      RID: linux-x64
      ZIP_FILE: roadcaptain-app-web-prod-${{ github.sha }}.tar.gz

    steps:
    - uses: actions/checkout@v3
    
    - name: Publish API
      # Because of reasons we need to explicitly set RuntimeIdentifiers to only win-x64 because MSBuild sets it to osx-x64;win-x64
      run: dotnet publish --no-self-contained -c ${{ env.CONFIGURATION }} -r ${{ env.RID }} -p:RuntimeIdentifiers=${{ env.RID }}-o ./publish src/RoadCaptain.App.Web/RoadCaptain.App.Web.csproj 
    
    - name: Create ZIP archive
      run: tar -zcf "${{ github.workspace }}/${{ env.ZIP_FILE }}" *
      working-directory: ./publish
      
    - name: Setup SSH key
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.SSH_SITE_KEY }}"
    
    - name: Copy artifacts to server
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: scp -r -o "StrictHostKeyChecking no" "${{ github.workspace }}/${{ env.ZIP_FILE }}" roadcaptain@roadcaptain.nl:/opt/roadcaptain/${{ env.ZIP_FILE }}
    
    - name: Extract artifacts on server
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: ssh -o "StrictHostKeyChecking no" roadcaptain@roadcaptain.nl 'systemctl stop --user RoadCaptainApiProd; cd /opt/roadcaptain/api-prod; tar -zxf /opt/roadcaptain/${{ env.ZIP_FILE }}; systemctl start --user RoadCaptainApiProd; rm -f /opt/roadcaptain/roadcaptain-app-web-prod-*.tar.gz'
